---
######
## Destroys chef solo materials
######

- name: Destroy chef-solo tmp files
  file:
    state: abstent
    path: "{{ chef_solo_runner_solo_path }}"
  when: chef_solo_runner_destroy_solo_materials|bool
