---
######
## Destroys chef solo materials
######

- name: Destroy chef-solo tmp files
  file:
    path: "{{ chef_solo_runner_solo_path }}"
    state: absent
  when: chef_solo_runner_destroy_solo_materials|bool
