---
######
## Create all chef-solo required materials on the target
######

###
# Clean target environment from old chef materials
- include: destroy_chef_solo_materials.yml
  chef_solo_runner_destroy_solo_materials: true

###
# Necessary structure and files

- name: Create directory chef-solo
  file:
    path: "{{ chef_solo_runner_solo_path }}"
    mode: '0777'
    state: directory

- name: Generate solo.rb
  template:
    src: "solo.rb.j2"
    dest: "{{ chef_solo_runner_solo_path }}/solo.rb"
    mode: '0666'
    force: yes

- name: Copying node.json
  copy:
    src: "{{ chef_solo_runner_node_json_file }}"
    dest: "{{ chef_solo_runner_solo_path }}"
    mode: '0666'
    directory_mode: '0777'
    force: yes

- name: Copying cookbooks archive
  copy:
    src: "{{ chef_solo_runner_cookbook_archive_file }}"
    dest: "{{ chef_solo_runner_solo_path }}/cookbooks.tar.gz"
    mode: '0666'
    force: yes

- name: Untar cookbooks archive
  shell: |
      tar -C "{{ chef_solo_runner_solo_path }}" \
        --no-same-permissions \
        --no-overwrite-dir \
        --no-same-owner \
        -xzm \
        -f "{{ chef_solo_runner_solo_path }}/cookbooks.tar.gz"

- name: Change permissions to unpackaged cookbooks tree
  file:
    path: "{{ chef_solo_runner_solo_path }}/cookbooks"
    mode: '0777'
    recurse: true
    state: directory

###
# Optional files

- name: Copying environments
  copy:
    src: "{{ chef_solo_runner_environments_dir }}"
    dest: "{{ chef_solo_runner_solo_path }}"
    force: yes
    mode: '0666'
    directory_mode: '0777'
  when: chef_solo_runner_environments_dir != ""

- name: Copying roles
  copy:
    src: "{{ chef_solo_runner_encrypted_data_bag_secret_file }}"
    dest: "{{ chef_solo_runner_solo_path }}"
    force: yes
    mode: '0666'
    directory_mode: '0777'
  when: chef_solo_runner_roles_dir != ""

- name: Copying encrypted_data_bag_key
  copy:
    src: "{{ chef_solo_runner_encrypted_data_bag_secret_file }}"
    dest: "{{ chef_solo_runner_solo_path }}"
    force: yes
    mode: '0666'
  when: chef_solo_runner_encrypted_data_bag_secret_file != ""

- name: Copying data bags
  copy:
    src: "{{ chef_solo_runner_data_bags_dir }}"
    dest: "{{ chef_solo_runner_solo_path }}"
    force: yes
    mode: '0666'
    directory_mode: '0777'
  when: chef_solo_runner_data_bags_dir != ""
